// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAL.DAL.Models;

namespace TAL_API.Migrations
{
    [DbContext(typeof(TALDBContext))]
    partial class TALDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TAL.DAL.Models.Occupation", b =>
                {
                    b.Property<int>("OccupationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OccupationName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OccupationRatingRefId")
                        .HasColumnType("int");

                    b.HasKey("OccupationId");

                    b.HasIndex("OccupationRatingRefId");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            OccupationId = 1,
                            OccupationName = "Cleaner",
                            OccupationRatingRefId = 3
                        },
                        new
                        {
                            OccupationId = 2,
                            OccupationName = "Doctor",
                            OccupationRatingRefId = 1
                        },
                        new
                        {
                            OccupationId = 3,
                            OccupationName = "Author",
                            OccupationRatingRefId = 2
                        },
                        new
                        {
                            OccupationId = 4,
                            OccupationName = "Farmer",
                            OccupationRatingRefId = 4
                        },
                        new
                        {
                            OccupationId = 5,
                            OccupationName = "Mechanic",
                            OccupationRatingRefId = 4
                        },
                        new
                        {
                            OccupationId = 6,
                            OccupationName = "Florist",
                            OccupationRatingRefId = 3
                        });
                });

            modelBuilder.Entity("TAL.DAL.Models.OccupationRating", b =>
                {
                    b.Property<int>("OccupationRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("OccupationRatingName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OccupationRatingId");

                    b.ToTable("OccupationRating");

                    b.HasData(
                        new
                        {
                            OccupationRatingId = 1,
                            Factor = 1.0m,
                            OccupationRatingName = "Professional"
                        },
                        new
                        {
                            OccupationRatingId = 2,
                            Factor = 1.25m,
                            OccupationRatingName = "White Collar"
                        },
                        new
                        {
                            OccupationRatingId = 3,
                            Factor = 1.50m,
                            OccupationRatingName = "Light Manual"
                        },
                        new
                        {
                            OccupationRatingId = 4,
                            Factor = 1.75m,
                            OccupationRatingName = "Heavy Manual"
                        });
                });

            modelBuilder.Entity("TAL.DAL.Models.Occupation", b =>
                {
                    b.HasOne("TAL.DAL.Models.OccupationRating", "OccupationRating")
                        .WithMany()
                        .HasForeignKey("OccupationRatingRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccupationRating");
                });
#pragma warning restore 612, 618
        }
    }
}
